#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Corrige acentos ausentes em palestras.json (ASCII → UTF-8 correto)."""
import json, re, pathlib, sys

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC  = ROOT / "assets" / "data" / "palestras.json"

FIXES = [
    (r'\btambem\b','também'),(r'\bTambem\b','Também'),
    (r'\bvoces\b','vocês'),(r'\bVoces\b','Vocês'),
    (r'\bvoce\b','você'),(r'\bVoce\b','Você'),
    (r'\bestao\b','estão'),(r'\bEstao\b','Estão'),
    (r'\balem\b','além'),(r'\bAlem\b','Além'),
    (r'\bnao\b','não'),(r'\bNao\b','Não'),
    # é (verb ser/estar) — targeted patterns to avoid breaking conjunction "e"
    (r'\be (ajustado|adaptado|realizado|desenvolvid[ao]|indicad[ao]|voltad[ao]|estruturad[ao]|direcionad[ao]|ministrad[ao]|personalizado|oferecid[ao]|definid[ao]|considerad[ao]|reconhecid[ao]|promovid[ao]|aplicad[ao]|garantid[ao]|uma |um )\b', r'é \1'),
    (r'\be necessari[ao]\b', 'é necessário'),
    (r'\be fundamental\b', 'é fundamental'),
    (r'\be importante\b', 'é importante'),
    (r'\be essencial\b', 'é essencial'),
    (r'\be possivel\b', 'é possível'),
    (r'\be obrigatorio\b', 'é obrigatório'),
    (r'\be composta\b', 'é composta'),
    (r'\be composto\b', 'é composto'),
    (r'\be ideal\b', 'é ideal'),
    (r'\be um\b', 'é um'),
    (r'\be uma\b', 'é uma'),
    # à (preposition a + accent, before feminine noun phrase)
    (r'\badaptada a nossa\b', 'adaptada à nossa'),
    (r'\badaptada a sua\b', 'adaptada à sua'),
    (r'\bde acordo a\b', 'de acordo à'),
    (r'\brelativa a\b', 'relativa à'),
    (r'\bsao\b','são'),(r'\bSao\b','São'),
    (r'\bidentificacao\b','identificação'),(r'\bIdentificacao\b','Identificação'),
    (r'\bapresentacao\b','apresentação'),(r'\bApresentacao\b','Apresentação'),
    (r'\bqualificacao\b','qualificação'),
    (r'\bcapacitacao\b','capacitação'),(r'\bCapacitacao\b','Capacitação'),
    (r'\bcontribuicao\b','contribuição'),
    (r'\bmanutencao\b','manutenção'),
    (r'\bcompreensao\b','compreensão'),
    (r'\brecuperacao\b','recuperação'),
    (r'\bconcentracao\b','concentração'),
    (r'\bsolicitacoes\b','solicitações'),(r'\bsolicitacao\b','solicitação'),(r'\bSolicitacao\b','Solicitação'),
    (r'\bintervencoes\b','intervenções'),(r'\bintervencao\b','intervenção'),(r'\bIntervencao\b','Intervenção'),
    (r'\bvalorizacao\b','valorização'),(r'\bValorizacao\b','Valorização'),
    (r'\bdiagnosticos\b','diagnósticos'),(r'\bdiagnostico\b','diagnóstico'),(r'\bDiagnostico\b','Diagnóstico'),
    (r'\borientacoes\b','orientações'),(r'\borientacao\b','orientação'),(r'\bOrientacao\b','Orientação'),
    (r'\binformacoes\b','informações'),(r'\binformacao\b','informação'),(r'\bInformacao\b','Informação'),
    (r'\bcolaboracao\b','colaboração'),(r'\bColaboracao\b','Colaboração'),
    (r'\borganizacao\b','organização'),(r'\bOrganizacao\b','Organização'),
    (r'\bparticipacao\b','participação'),(r'\bParticipacao\b','Participação'),
    (r'\bcomunicacao\b','comunicação'),(r'\bComunicacao\b','Comunicação'),
    (r'\bavaliacao\b','avaliação'),(r'\bAvaliacao\b','Avaliação'),
    (r'\bintegracao\b','integração'),(r'\bIntegracao\b','Integração'),
    (r'\binteracao\b','interação'),(r'\bInteracao\b','Interação'),
    (r'\bformacao\b','formação'),
    (r'\bpercepcao\b','percepção'),
    (r'\boperacoes\b','operações'),(r'\boperacao\b','operação'),
    (r'\bproducao\b','produção'),(r'\bProducao\b','Produção'),
    (r'\bpromocao\b','promoção'),(r'\bPromocao\b','Promoção'),
    (r'\breducao\b','redução'),(r'\bReducao\b','Redução'),
    (r'\bprotecao\b','proteção'),(r'\bProtecao\b','Proteção'),
    (r'\bprevencao\b','prevenção'),(r'\bPrevencao\b','Prevenção'),
    (r'\bposicoes\b','posições'),(r'\bposicao\b','posição'),
    (r'\bdecisoes\b','decisões'),(r'\bdecisao\b','decisão'),
    (r'\bsituacoes\b','situações'),(r'\bsituacao\b','situação'),(r'\bSituacao\b','Situação'),
    (r'\brelacoes\b','relações'),(r'\brelacao\b','relação'),(r'\bRelacao\b','Relação'),
    (r'\bfuncoes\b','funções'),(r'\bfuncao\b','função'),(r'\bFuncao\b','Função'),
    (r'\bcondicoes\b','condições'),(r'\bCondicoes\b','Condições'),(r'\bcondicao\b','condição'),
    (r'\bquestoes\b','questões'),(r'\bquestao\b','questão'),(r'\bQuestao\b','Questão'),
    (r'\bsolucoes\b','soluções'),(r'\bsolucao\b','solução'),(r'\bSolucao\b','Solução'),
    (r'\bacoes\b','ações'),(r'\bacao\b','ação'),(r'\bAcao\b','Ação'),
    (r'\batencao\b','atenção'),(r'\bAtencao\b','Atenção'),
    (r'\bgestao\b','gestão'),(r'\bGestao\b','Gestão'),
    (r'\blicoes\b','lições'),(r'\blicao\b','lição'),
    (r'\binclusao\b','inclusão'),(r'\bInclusao\b','Inclusão'),
    (r'\bdinamicas\b','dinâmicas'),(r'\bdinamica\b','dinâmica'),(r'\bDinamica\b','Dinâmica'),
    (r'\bgeneros\b','gêneros'),(r'\bgenero\b','gênero'),(r'\bGenero\b','Gênero'),
    (r'\bpadroes\b','padrões'),(r'\bpadrao\b','padrão'),(r'\bPadrao\b','Padrão'),
    (r'\bcronicos\b','crônicos'),(r'\bcronica\b','crônica'),(r'\bCronica\b','Crônica'),
    (r'\bsindromes\b','síndromes'),(r'\bsindrome\b','síndrome'),(r'\bSindrome\b','Síndrome'),
    (r'\bfuncionarios\b','funcionários'),(r'\bFuncionarios\b','Funcionários'),
    (r'\bfuncionario\b','funcionário'),(r'\bFuncionario\b','Funcionário'),
    (r'\bpublicos\b','públicos'),(r'\bpublico\b','público'),(r'\bPublico\b','Público'),
    (r'\bconteudos\b','conteúdos'),(r'\bconteudo\b','conteúdo'),(r'\bConteudo\b','Conteúdo'),
    (r'\bhistorias\b','histórias'),(r'\bhistoria\b','história'),(r'\bHistoria\b','História'),
    (r'\btopicos\b','tópicos'),(r'\bTopicos\b','Tópicos'),(r'\btopico\b','tópico'),
    (r'\bpaginas\b','páginas'),(r'\bpagina\b','página'),
    (r'\bnumeros\b','números'),(r'\bnumero\b','número'),
    (r'\bregioes\b','regiões'),(r'\bregiao\b','região'),(r'\bRegiao\b','Região'),
    (r'\bduvidas\b','dúvidas'),(r'\bDuvidas\b','Dúvidas'),(r'\bduvida\b','dúvida'),(r'\bDuvida\b','Dúvida'),
    (r'\bhabitos\b','hábitos'),(r'\bHabitos\b','Hábitos'),(r'\bhabito\b','hábito'),
    (r'\bmedicas\b','médicas'),(r'\bmedicos\b','médicos'),
    (r'\bmedica\b','médica'),(r'\bMedica\b','Médica'),
    (r'\bmedico\b','médico'),(r'\bMedico\b','Médico'),
    (r'\bperiodos\b','períodos'),(r'\bperiodo\b','período'),(r'\bPeriodo\b','Período'),
    (r'\bespecificos\b','específicos'),(r'\bespecificas\b','específicas'),
    (r'\bespecifica\b','específica'),(r'\bEspecifica\b','Específica'),
    (r'\bespecifico\b','específico'),(r'\bEspecifico\b','Específico'),
    (r'\btecnicos\b','técnicos'),(r'\btecnicas\b','técnicas'),
    (r'\btecnica\b','técnica'),(r'\bTecnica\b','Técnica'),
    (r'\btecnico\b','técnico'),(r'\bTecnico\b','Técnico'),
    (r'\bpraticos\b','práticos'),(r'\bpraticas\b','práticas'),
    (r'\bpratica\b','prática'),(r'\bPratica\b','Prática'),
    (r'\bpratico\b','prático'),(r'\bPratico\b','Prático'),
    (r'\bbasicos\b','básicos'),(r'\bbasicas\b','básicas'),
    (r'\bbasica\b','básica'),(r'\bBasica\b','Básica'),
    (r'\bbasico\b','básico'),(r'\bBasico\b','Básico'),
    (r'\bproprios\b','próprios'),(r'\bproprias\b','próprias'),
    (r'\bpropria\b','própria'),(r'\bproprio\b','próprio'),
    (r'\bpossivel\b','possível'),(r'\bPossivel\b','Possível'),
    (r'\bdisponivel\b','disponível'),(r'\bDisponivel\b','Disponível'),
    (r'\buteis\b','úteis'),(r'\butil\b','útil'),(r'\bUtil\b','Útil'),
    (r'\bfaceis\b','fáceis'),(r'\bfacil\b','fácil'),(r'\bFacil\b','Fácil'),
    (r'\bdificeis\b','difíceis'),(r'\bdificil\b','difícil'),
    (r'\bpsicologicos\b','psicológicos'),(r'\bpsicologica\b','psicológica'),(r'\bpsicologico\b','psicológico'),
    (r'\bfisicas\b','físicas'),(r'\bfisicos\b','físicos'),
    (r'\bfisica\b','física'),(r'\bFisica\b','Física'),
    (r'\bfisico\b','físico'),
    (r'\bmusculo\b','músculo'),
    (r'\beconomicos\b','econômicos'),(r'\beconomica\b','econômica'),(r'\beconomico\b','econômico'),
    (r'\btraumaticos\b','traumáticos'),(r'\btraumatico\b','traumático'),
    (r'\bclinicas\b','clínicas'),(r'\bclinica\b','clínica'),(r'\bclinico\b','clínico'),
    (r'\bsuicidio\b','suicídio'),(r'\bSuicidio\b','Suicídio'),
    (r'\blideranca\b','liderança'),(r'\bLideranca\b','Liderança'),
    (r'\blider\b','líder'),(r'\bLider\b','Líder'),
    (r'\borcamentos\b','orçamentos'),(r'\borcamento\b','orçamento'),(r'\bOrcamento\b','Orçamento'),
    (r'\bcoracoes\b','corações'),(r'\bcoracao\b','coração'),(r'\bCoracao\b','Coração'),
    (r'\bimportancia\b','importância'),(r'\bImportancia\b','Importância'),
    (r'\bpresenteismo\b','presenteísmo'),
    (r'\binicio\b','início'),(r'\bInicio\b','Início'),
    (r'\bproximos\b','próximos'),(r'\bproximo\b','próximo'),
    (r'\btensoes\b','tensões'),(r'\btensao\b','tensão'),
    (r'\bpressoes\b','pressões'),(r'\bpressao\b','pressão'),
    (r'\bemocoes\b','emoções'),(r'\bemocao\b','emoção'),
    (r'\bcompassao\b','compaixão'),
    (r'\baceitacao\b','aceitação'),(r'\bAceitacao\b','Aceitação'),
    (r'\buniao\b','união'),(r'\bUniao\b','União'),
    (r'\benfase\b','ênfase'),
    (r'\bsaude\b','saúde'),(r'\bSaude\b','Saúde'),
    (r'\borgaos\b','órgãos'),(r'\borgao\b','órgão'),
    (r'\bcriacao\b','criação'),(r'\bCriacao\b','Criação'),
    (r'\bpatrimonio\b','patrimônio'),
    (r'\bsindrome\b','síndrome'),
    (r'\bperiodo\b','período'),
    (r'\bexpansao\b','expansão'),
    (r'\badesao\b','adesão'),
    (r'\bdiagnostico\b','diagnóstico'),
    (r'\bproximo\b','próximo'),
    (r'\blicao\b','lição'),
    (r'\bpresenteismo\b','presenteísmo'),
    (r'\bnacao\b','nação'),
    (r'\banimo\b','ânimo'),
    (r'\bheroi\b','herói'),
    (r'\bintencao\b','intenção'),
    (r'\balguem\b','alguém'),(r'\bAlguem\b','Alguém'),
    (r'\bninguem\b','ninguém'),
    (r'\bmudancas\b','mudanças'),(r'\bMudancas\b','Mudanças'),
    (r'\bmudanca\b','mudança'),(r'\bMudanca\b','Mudança'),
    (r'\bcomercio\b','comércio'),
    (r'\bdecadas\b','décadas'),(r'\bdecada\b','década'),
    (r'\bconsequencias\b','consequências'),(r'\bconsequencia\b','consequência'),
    (r'\bdiferencas\b','diferenças'),(r'\bdiferenca\b','diferença'),
    (r'\bexperiencias\b','experiências'),(r'\bexperiencia\b','experiência'),
    (r'\bpresencas\b','presenças'),(r'\bpresenca\b','presença'),
    (r'\bcomecam\b','começam'),(r'\bcomecamos\b','começamos'),(r'\bcomeca\b','começa'),
    (r'\balmoco\b','almoço'),
    (r'\bforcas\b','forças'),(r'\bforca\b','força'),
    (r'\bameacas\b','ameaças'),(r'\bameaca\b','ameaça'),
    (r'\bdiscussoes\b','discussões'),(r'\bdiscussao\b','discussão'),
    (r'\bque e\b','que é'),
    (r'\bEle e\b','Ele é'),(r'\bEla e\b','Ela é'),
    (r'\bIsso e\b','Isso é'),
    (r'\besto e\b','esto é'),
    (r'\bdesesperancas\b','desesperanças'),(r'\bdesesperanca\b','desesperança'),
    (r'\besperancas\b','esperanças'),(r'\besperanca\b','esperança'),
    (r'\bsemelhancas\b','semelhanças'),(r'\bsemelhanca\b','semelhança'),
    (r'\bvivencias\b','vivências'),(r'\bvivencia\b','vivência'),
    (r'\bconfiancas\b','confianças'),(r'\bconfianca\b','confiança'),
    (r'\bherancas\b','heranças'),(r'\bheranca\b','herança'),
    (r'\binstancias\b','instâncias'),(r'\binstancia\b','instância'),
    (r'\btransicao\b','transição'),(r'\bTransicao\b','Transição'),
    (r'\bproporcionar\b','proporcionar'),
    (r'\bpromover\b','promover'),
    # Saúde feminina / masculina
    (r'\bcancer\b','câncer'),(r'\bCancer\b','Câncer'),
    (r'\bprostata\b','próstata'),(r'\bProstata\b','Próstata'),
    (r'\begoismo\b','egoísmo'),(r'\bEgoismo\b','Egoísmo'),
    (r'\bdepressao\b','depressão'),(r'\bDepressao\b','Depressão'),
    (r'\bdepressoes\b','depressões'),
    (r'\bresistencia\b','resistência'),(r'\bResistencia\b','Resistência'),
    (r'\bprogramacoes\b','programações'),(r'\bprogramacao\b','programação'),(r'\bProgramacao\b','Programação'),
    (r'\bcombinacao\b','combinação'),(r'\bCombinacao\b','Combinação'),
    (r'\bestagio\b','estágio'),(r'\bEstagio\b','Estágio'),
    (r'\bestudos\b','estudos'),
    (r'\bagil\b','ágil'),(r'\bAgil\b','Ágil'),
    (r'\brapido\b','rápido'),(r'\brapidos\b','rápidos'),(r'\brapida\b','rápida'),
    (r'\bdecoracao\b','decoração'),
    (r'\bplanejamento\b','planejamento'),
    (r'\bplanejamentos\b','planejamentos'),
    # segurança / convenção
    (r'\bsegurancas\b','seguranças'),(r'\bseguranca\b','segurança'),(r'\bSeguranca\b','Segurança'),
    (r'\bconvencao\b','convenção'),(r'\bConvencao\b','Convenção'),
    (r'\badaptacao\b','adaptação'),(r'\bAdaptacao\b','Adaptação'),
    (r'\bregulamentacao\b','regulamentação'),
    (r'\bfiscalizacao\b','fiscalização'),
    (r'\bcontratacao\b','contratação'),
    # acessível / responsável / disponível / possível (já tem mas reforça)
    (r'\bacessiveis\b','acessíveis'),(r'\bacessivel\b','acessível'),(r'\bAcessivel\b','Acessível'),
    (r'\bresponsaveis\b','responsáveis'),(r'\bresponsavel\b','responsável'),
    (r'\bresponsável\b','responsável'),
    (r'\bavancado\b','avançado'),(r'\bavancada\b','avançada'),
    # não é (after "não", the following "e" is almost always the verb "é")
    (r'\bnão e\b','não é'),
    # às (preposition a+s before plural feminine)
    (r'\bas Regras\b','às Regras'),
    (r'\bas normas\b','às normas'),
    (r'\bas diretrizes\b','às diretrizes'),
    (r'\bas equipes\b','às equipes'),
    (r'\bas empresas\b','às empresas'),
    # Sentence-initial É (verb ser) — "E conduzida" → "É conduzida"
    (r'^E (conduzida|conduzido|realizada|realizado|voltada|voltado|indicada|indicado|adequada|adequado|desenvolvida|desenvolvido|ministrada|ministrado|composta|composto|baseada|baseado|criada|criado|possivel|uma |um |gratuita|gratuito|feita|feito|permitida|permitido)\b',
     r'É \1'),
    # mid-sentence "? E " beginning of new sentence after ?
    (r'([?])\s+E (conduzida|conduzido|realizada|realizado|voltada|voltado|indicada|indicado)',
     r'\1 É \2'),
]

def fix_text(s):
    if not isinstance(s, str):
        return s
    for p, r in FIXES:
        s = re.sub(p, r, s, flags=re.MULTILINE)
    return s

def fix_obj(o):
    if isinstance(o, str):   return fix_text(o)
    if isinstance(o, list):  return [fix_obj(i) for i in o]
    if isinstance(o, dict):  return {k: fix_obj(v) for k, v in o.items()}
    return o

data  = json.loads(SRC.read_text(encoding='utf-8'))
fixed = fix_obj(data)
SRC.write_text(json.dumps(fixed, ensure_ascii=False, indent=2), encoding='utf-8')

p0 = fixed['palestras'][0]
print('titulo:', p0['titulo'])
print('faq q0:', p0['faq'][0]['q'])
print('topico0:', p0['topicos'][0])
for pk in fixed['palestras']:
    if pk['slug'] == 'saude-mental':
        print('sm sobre:', pk['sobre'][:60])
print('Done.')
